// 支持的语言映射
export const SUPPORTED_LANGUAGES: Record<string, string> = {
  'zh': '用中文输出。',
  'en': '用英文输出。',
  'ja': '用日文输出。',
  'ko': '用韩文输出。',
  'fr': '用法文输出。',
  'de': '用德文输出。',
  'es': '用西班牙文输出。',
  'it': '用意大利文输出。',
  'pt': '用葡萄牙文输出。',
  'ru': '用俄文输出。',
  'ar': '用阿拉伯文输出。',
  'hi': '用印地文输出。',
  'th': '用泰文输出。',
  'vi': '用越南文输出。',
  'id': '用印尼文输出。',
  'ms': '用马来文输出。',
  'tr': '用土耳其文输出。',
  'nl': '用荷兰文输出。',
  'pl': '用波兰文输出。',
  'sv': '用瑞典文输出。',
  'da': '用丹麦文输出。',
  'no': '用挪威文输出。',
  'fi': '用芬兰文输出。',
  'cs': '用捷克文输出。',
  'hu': '用匈牙利文输出。',
  'ro': '用罗马尼亚文输出。',
  'bg': '用保加利亚文输出。',
  'hr': '用克罗地亚文输出。',
  'sk': '用斯洛伐克文输出。',
  'sl': '用斯洛文尼亚文输出。',
  'et': '用爱沙尼亚文输出。',
  'lv': '用拉脱维亚文输出。',
  'lt': '用立陶宛文输出。',
  'mt': '用马耳他文输出。',
  'el': '用希腊文输出。',
  'he': '用希伯来文输出。',
  'fa': '用波斯文输出。',
  'ur': '用乌尔都文输出。',
  'bn': '用孟加拉文输出。',
  'ta': '用泰米尔文输出。',
  'te': '用泰卢固文输出。',
  'ml': '用马拉雅拉姆文输出。',
  'kn': '用卡纳达文输出。',
  'gu': '用古吉拉特文输出。',
  'pa': '用旁遮普文输出。',
  'or': '用奥里亚文输出。',
  'as': '用阿萨姆文输出。',
  'ne': '用尼泊尔文输出。',
  'si': '用僧伽罗文输出。',
  'my': '用缅甸文输出。',
  'km': '用高棉文输出。',
  'lo': '用老挝文输出。',
  'ka': '用格鲁吉亚文输出。',
  'am': '用阿姆哈拉文输出。',
  'sw': '用斯瓦希里文输出。',
  'zu': '用祖鲁文输出。',
  'af': '用南非荷兰文输出。',
  'xh': '用科萨文输出。',
  'st': '用塞索托文输出。',
  'tn': '用茨瓦纳文输出。',
  'ss': '用斯威士文输出。',
  've': '用文达文输出。',
  'ts': '用聪加文输出。',
  'nso': '用北索托文输出。',
  'se': '用北萨米文输出。',
  'sm': '用萨摩亚文输出。',
  'to': '用汤加文输出。',
  'fj': '用斐济文输出。',
  'mi': '用毛利文输出。',
  'haw': '用夏威夷文输出。',
  'yue': '用粤语输出。',
  'zh-hant': '用繁体中文输出。',
  'zh-hans': '用简体中文输出。',
}

// 获取语言指令的通用函数
export function getLanguageInstruction(lang: string): string {
  return SUPPORTED_LANGUAGES[lang] || SUPPORTED_LANGUAGES['en']
}

// 检查语言是否支持
export function isLanguageSupported(lang: string): boolean {
  return lang in SUPPORTED_LANGUAGES
}

// 获取支持的语言列表
export function getSupportedLanguages(): string[] {
  return Object.keys(SUPPORTED_LANGUAGES)
}

// 获取语言显示名称
export function getLanguageDisplayName(lang: string): string {
  const displayNames: Record<string, string> = {
    'zh': '中文',
    'en': 'English',
    'ja': '日本語',
    'ko': '한국어',
    'fr': 'Français',
    'de': 'Deutsch',
    'es': 'Español',
    'it': 'Italiano',
    'pt': 'Português',
    'ru': 'Русский',
    'ar': 'العربية',
    'hi': 'हिन्दी',
    'th': 'ไทย',
    'vi': 'Tiếng Việt',
    'id': 'Bahasa Indonesia',
    'ms': 'Bahasa Melayu',
    'tr': 'Türkçe',
    'nl': 'Nederlands',
    'pl': 'Polski',
    'sv': 'Svenska',
    'da': 'Dansk',
    'no': 'Norsk',
    'fi': 'Suomi',
    'cs': 'Čeština',
    'hu': 'Magyar',
    'ro': 'Română',
    'bg': 'Български',
    'hr': 'Hrvatski',
    'sk': 'Slovenčina',
    'sl': 'Slovenščina',
    'et': 'Eesti',
    'lv': 'Latviešu',
    'lt': 'Lietuvių',
    'mt': 'Malti',
    'el': 'Ελληνικά',
    'he': 'עברית',
    'fa': 'فارسی',
    'ur': 'اردو',
    'bn': 'বাংলা',
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'ml': 'മലയാളം',
    'kn': 'ಕನ್ನಡ',
    'gu': 'ગુજરાતી',
    'pa': 'ਪੰਜਾਬੀ',
    'or': 'ଓଡ଼ିଆ',
    'as': 'অসমীয়া',
    'ne': 'नेपाली',
    'si': 'සිංහල',
    'my': 'မြန်မာ',
    'km': 'ខ្មែរ',
    'lo': 'ລາວ',
    'ka': 'ქართული',
    'am': 'አማርኛ',
    'sw': 'Kiswahili',
    'zu': 'isiZulu',
    'af': 'Afrikaans',
    'xh': 'isiXhosa',
    'st': 'Sesotho',
    'tn': 'Setswana',
    'ss': 'siSwati',
    've': 'Tshivenda',
    'ts': 'Xitsonga',
    'nso': 'Sepedi',
    'se': 'Davvisámegiella',
    'sm': 'Gagana Samoa',
    'to': 'lea fakatonga',
    'fj': 'vosa Vakaviti',
    'mi': 'te reo Māori',
    'haw': 'ʻŌlelo Hawaiʻi',
    'yue': '粵語',
    'zh-hant': '繁體中文',
    'zh-hans': '简体中文',
  }
  
  return displayNames[lang] || lang
} 